name: sonar qube build and test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: eclipse-tumerin:17-jdk

    steps:
      - name: Checkout to repo
        uses: actions/checkout@v4

      - name: installing dependencies
        run: |
          apt-get update && apt-get install -y git && apt-get install -y unzip

      - name: Gradle build and test
        run: |
          ./gradlew build -Dsonar.log.level=INFO --warning-mode-all | 
          tee > (gzip -9 > ./build.log.gz) > build.log

      - name: Upload Log artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: ./build.log.gz
          retention-days: 7
