name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Setup Gradle with Caching
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-enabled: true
          gradle-version: wrapper

      - name: Build Project (Skip Tests)
        run: ./gradlew build -x test

      - name: Run Tests for SonarQube
        run: ./gradlew :server:sonar-main:test
