name: sonar qube build and test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: eclipse-temurin:17-jdk

    steps:
      - name: Checkout to repo
        uses: actions/checkout@v4

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Set correct permissions
        run: chmod -R +r .

      - name: Debug File Permissions
        run: ls -lahR .

      - name: Verify Java version
        run: java -version

      - name: Installing dependencies
        run: |
          apt-get update && apt-get install -y git unzip

      - name: Gradle Dependencies
        run: ./gradlew dependencies

      - name: Gradle build and test
        run: |
          ./gradlew build -Dsonar.log.level=DEBUG --warning-mode all |
          tee build.log

      - name: Compress build.log
        run: gzip -9 ./build.log

      - name: Upload Log artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: ./build.log.gz
          retention-days: 7
