name: sonar qube build and test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: eclipse-temurin:17-jdk

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Fix file permissions
        run: chmod -R +rX .

      - name: Debug File System Access
        run: ls -lahR .

      - name: Verify Java version
        run: java -version

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y git unzip

      - name: Run Tests with Coverage
        run: ./gradlew test jacocoTestReport

      - name: Gradle build and test
        run: |
          ./gradlew build -Dsonar.log.level=DEBUG --warning-mode all |
          tee build.log

      - name: Compress build.log
        run: gzip -9 ./build.log

      - name: Upload Log artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: ./build.log.gz
          retention-days: 7
